apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chmse77ft-go 
  janus-idp.io/tekton: chmse77ft-go
  backstage.io/kubernetes-id: chmse77ft-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chmse77ft-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml